server:
  port: 8989
  servlet:
    context-path: /yingxuetao
    jsp:
      init-parameters:
        development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123654
    url: jdbc:mysql://localhost:3306/yingxue?serverTimezone=UTC
    #    ?serverTimezone=UTC    ?serverTimeZone=GMT
  mvc:
    view:
      prefix: /
      suffix: .jsp
mybatis:
  mapper-locations: classpath:com/baizhi/mapper/*Mapper.xml
  type-aliases-package: com.baizhi.entity